### ISSUE TITLE
Running multiple instances

### ISSUE THREAD

**Issue by Danappelxx** [jakeheis/ZewoFlock#1]
Hi! I just found this project and think its very cool. I just wanted to let you know that the recommended way of deploying Zewo applications is to launch as many processes are there are logical cores, since Zewo uses a single-threaded coroutine system for concurrency. The number of cores can be found by running `nproc`. It looks like the way its done right now is just running a single process, which works fine but doesn't take advantage of the whole machine.

**Comment by jakeheis** [comment]
2db49c241fd08ae17bf9afe929eb69a2e7166721 and e5bf3eca69aeba6cb6ee6e98cd8e98de1874a213 should take care of this!

If there's any other features Flock or ZewoFlock lacks which would be helpful to Zewo developers, feel free to open more issues -- I'd like Flock to be as useful to Zewo developers as possible

**Comment by Danappelxx** [comment]
Looks like this came back? I saw in this commit https://github.com/jakeheis/ZewoFlock/commit/1f991bf3234e913f7380798f7cee3a69c73e0f1a that you were getting an "address already in use" error. To fix that, add the `reusePort: true` parameter to the server initializer (this will be done by default in the next version of Zewo).

**Comment by jakeheis** [comment]
Ah okay that's one way to fix it. I'm curious what Zewo's take is on systemd starting a master process which forks workers rather than having systemd itself manage the multiple processes. That's the approach Ruby's Unicorn takes (which is why a single `unicorn` call is enough to start multiple processes rather than having to call it `nproc` number of times) and is the approach https://github.com/kylef/Curassow was headed in. That doesn't mean Zewo needs to go in that direction, as it is possible to spawn multiple daemonized Zewo processes using this Flock system (albeit systemd was not built for this sort of use so its a little strange/hacky), but I'm curious why Zewo chose to not mangage workers from within.

**Comment by Danappelxx** [comment]
We have tossed around the idea of a pre-forking model where we manages subprocesses on our own, but really that seems to be a task for a higher-level tool. Your example of unicorn is not packaged with rails or sinatra, and similarly uwsgi is not packaged with django or flask - even though both are widely recommended to be used.

Also, and forgive me if this is totally ignorant, but wouldn't supervisord be a better tool for the job rather than systemd and friends? Actually, I would even go so far as to say that it could make sense for Flock to _clone_ supervisord and manage the processes itself.

**Comment by jakeheis** [comment]
Thanks for the supervisord suggestion - I had not considered it before, but it fits the bill better than systemd does. Flock and ZewoFlock have been updated to use supervisord and spawn the correct number of processes
